- model_id: lms-qwen2.5
  model_name: qwen2.5-coder-32b-instruct-mlx
  api_base: "http://localhost:1234/v1/"
- model_id: lms-mistral
  model_name: mistral-small-3.1-24b-instruct-2503
  vision: true
  api_base: "http://localhost:1234/v1/"